### ISSUE TITLE
Is it possible to make Tabula Conditional?

### ISSUE THREAD

**Issue by HatedFate** [zhao-zilong/Tabula#13]
If I want to generate samples with a specific feature, is there any ways to do this in Tabula? For example, I want to sample 100 data points of people with the name "John Doe".

**Comment by zhao-zilong** [comment]
@HatedFate  yes, it is. Check this part of code: https://github.com/zhao-zilong/Tabula/blob/29cafbdb97c7fb61aa3318f7096f1e79e436a189/tabula/tabula.py#L234
