### ISSUE TITLE
There were no results after fit

### ISSUE THREAD

**Issue by coding-cadenza** [zhao-zilong/Tabula#4]
Why there are no results after fit，and no trained model?

![QQ截图20240229110204](https://github.com/zhao-zilong/Tabula/assets/71361767/68321ef7-5e55-480f-a0d1-08eb8dd91694)
![QQ截图20240229110214](https://github.com/zhao-zilong/Tabula/assets/71361767/2e0fcc62-8f1c-491a-aa0a-a74bce4dc865)

**Comment by zhao-zilong** [comment]
Hi @coding-cadenza 

Could you check this demo: https://github.com/zhao-zilong/Tabula/blob/main/Tabula_on_insurance_dataset.ipynb  
After you trained the model, you actually need to explicitly call some blocks of code to save the model and sample the data.

Hope to hear back from you soon.

Best,

Zilong

**Comment by coding-cadenza** [comment]
This issue is solved, thanks
